version: 2.1

jobs:
  deploy-prod-from-main:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Add deployment key fingerprint from prod repo for CircleCI to use for a push at https://github.com/CMSgov/MESCertificationRepo/settings/keys
      - add_ssh_keys:
          fingerprints:
            - "00:5c:4a:a0:67:2f:28:b1:81:83:b2:d3:40:da:c3:5e"
      # update this line when the repo is renamed
      - run: git remote add prod_repo git@github.com:CMSgov/CMCS-DSG-DSS-Certification.git
      - run:
          name: "Updating prod"
          command: "git push prod_repo main:main"

workflows:
  # Workflow to deploy staging repo changes to prod on changes to main
  deploy-prod-workflow:
    jobs:
      - deploy-prod-from-main:
          filters:
            branches:
              only:
                - main
